<?php

namespace Database\Seeders;

use App\Models\Admin\Brand\Brand;
use App\Models\Admin\Category\Category;
use App\Models\Admin\Collection\Collection;
use App\Models\Admin\Gender\Gender;
use App\Models\Admin\Product\Product;
use App\Models\Admin\ScentFamily\ScentFamily;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        $brands = Brand::all();
        $collections = Collection::all();
        $genders = Gender::all();
        $scentFamilies = ScentFamily::all();

        // Product data with variations
        $products = [
            // Category: Electronics - Brand: Apple
            [
                'name' => 'iPhone 15 Pro Max',
                'sku' => 'APPLE-IP15-001',
                'short_description' => 'Latest flagship smartphone with advanced features',
                'description' => 'Experience the power of iPhone 15 Pro Max with 5G connectivity and advanced camera system.',
                'price' => 1299.00,
                'compare_at_price' => 1399.00,
                'cost_price' => 800.00,
                'stock_quantity' => 50,
                'track_inventory' => true,
                'low_stock_threshold' => 10,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Apple',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'iPhone 15',
                'sku' => 'APPLE-IP15-002',
                'short_description' => 'Powerful smartphone with excellent camera',
                'description' => 'iPhone 15 with Dynamic Island and improved battery life.',
                'price' => 799.00,
                'compare_at_price' => 899.00,
                'cost_price' => 500.00,
                'stock_quantity' => 75,
                'track_inventory' => true,
                'low_stock_threshold' => 15,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Apple',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Apple Watch Series 9',
                'sku' => 'APPLE-WATCH-001',
                'short_description' => 'Advanced fitness and health tracker',
                'description' => 'Apple Watch Series 9 with Always-On Retina display.',
                'price' => 399.00,
                'compare_at_price' => 449.00,
                'cost_price' => 250.00,
                'stock_quantity' => 100,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Apple',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'MacBook Pro 16"',
                'sku' => 'APPLE-MBP-001',
                'short_description' => 'Powerful laptop for professionals',
                'description' => 'MacBook Pro with M3 Pro chip and stunning display.',
                'price' => 2499.00,
                'compare_at_price' => 2699.00,
                'cost_price' => 1500.00,
                'stock_quantity' => 30,
                'track_inventory' => true,
                'low_stock_threshold' => 5,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Electronics',
                'brand_name' => 'Apple',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'AirPods Pro',
                'sku' => 'APPLE-AP-001',
                'short_description' => 'Premium wireless earbuds with noise cancellation',
                'description' => 'AirPods Pro with active noise cancellation and transparency mode.',
                'price' => 249.00,
                'compare_at_price' => 299.00,
                'cost_price' => 150.00,
                'stock_quantity' => 200,
                'track_inventory' => true,
                'low_stock_threshold' => 30,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Apple',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],

            // Category: Electronics - Brand: Samsung
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'sku' => 'SAMSUNG-S24-001',
                'short_description' => 'Ultra flagship with advanced AI features',
                'description' => 'Samsung Galaxy S24 Ultra with Galaxy AI technology.',
                'price' => 1299.00,
                'compare_at_price' => 1399.00,
                'cost_price' => 750.00,
                'stock_quantity' => 45,
                'track_inventory' => true,
                'low_stock_threshold' => 10,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Samsung',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Samsung Galaxy S24',
                'sku' => 'SAMSUNG-S24-002',
                'short_description' => 'Flagship smartphone with 5G',
                'description' => 'Samsung Galaxy S24 with powerful performance.',
                'price' => 799.00,
                'compare_at_price' => 899.00,
                'cost_price' => 480.00,
                'stock_quantity' => 60,
                'track_inventory' => true,
                'low_stock_threshold' => 12,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Samsung',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Samsung Galaxy Tab S9 Ultra',
                'sku' => 'SAMSUNG-TAB-001',
                'short_description' => 'Large Android tablet for productivity',
                'description' => 'Samsung Galaxy Tab S9 Ultra with AMOLED display.',
                'price' => 1199.00,
                'compare_at_price' => 1299.00,
                'cost_price' => 700.00,
                'stock_quantity' => 35,
                'track_inventory' => true,
                'low_stock_threshold' => 8,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Electronics',
                'brand_name' => 'Samsung',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Samsung QLED 85" TV',
                'sku' => 'SAMSUNG-TV-001',
                'short_description' => '85-inch 4K Smart TV with quantum dots',
                'description' => 'Samsung 85" QLED TV with gaming features.',
                'price' => 2999.00,
                'compare_at_price' => 3299.00,
                'cost_price' => 1800.00,
                'stock_quantity' => 15,
                'track_inventory' => true,
                'low_stock_threshold' => 3,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Electronics',
                'brand_name' => 'Samsung',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Samsung Galaxy Buds2 Pro',
                'sku' => 'SAMSUNG-BUDS-001',
                'short_description' => 'Wireless earbuds with ANC',
                'description' => 'Samsung Galaxy Buds2 Pro with active noise cancellation.',
                'price' => 229.00,
                'compare_at_price' => 279.00,
                'cost_price' => 140.00,
                'stock_quantity' => 150,
                'track_inventory' => true,
                'low_stock_threshold' => 25,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Electronics',
                'brand_name' => 'Samsung',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],

            // Category: Clothing - Brand: Nike
            [
                'name' => 'Nike Air Max 90',
                'sku' => 'NIKE-AM90-001',
                'short_description' => 'Classic air cushioned sneaker',
                'description' => 'Nike Air Max 90 with iconic design.',
                'price' => 129.99,
                'compare_at_price' => 149.99,
                'cost_price' => 70.00,
                'stock_quantity' => 200,
                'track_inventory' => true,
                'low_stock_threshold' => 30,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Nike',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Nike React Infinity Run 2',
                'sku' => 'NIKE-REACT-001',
                'short_description' => 'Running shoe with React foam',
                'description' => 'Nike React Infinity Run with cushioning.',
                'price' => 159.99,
                'compare_at_price' => 179.99,
                'cost_price' => 90.00,
                'stock_quantity' => 120,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Clothing',
                'brand_name' => 'Nike',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Nike Dri-FIT T-Shirt',
                'sku' => 'NIKE-SHIRT-001',
                'short_description' => 'Moisture-wicking athletic shirt',
                'description' => 'Nike Dri-FIT Technology shirt.',
                'price' => 34.99,
                'compare_at_price' => 44.99,
                'cost_price' => 18.00,
                'stock_quantity' => 500,
                'track_inventory' => true,
                'low_stock_threshold' => 50,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Nike',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Nike Therma-FIT Hoodie',
                'sku' => 'NIKE-HOODIE-001',
                'short_description' => 'Warm athletic hoodie',
                'description' => 'Nike Therma-FIT hoodie for cold weather.',
                'price' => 89.99,
                'compare_at_price' => 109.99,
                'cost_price' => 50.00,
                'stock_quantity' => 150,
                'track_inventory' => true,
                'low_stock_threshold' => 25,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Clothing',
                'brand_name' => 'Nike',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Nike Training Shorts',
                'sku' => 'NIKE-SHORT-001',
                'short_description' => 'Lightweight training shorts',
                'description' => 'Nike shorts with built-in briefs.',
                'price' => 49.99,
                'compare_at_price' => 59.99,
                'cost_price' => 28.00,
                'stock_quantity' => 250,
                'track_inventory' => true,
                'low_stock_threshold' => 35,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Nike',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],

            // Category: Clothing - Brand: Adidas
            [
                'name' => 'Adidas Ultraboost 22',
                'sku' => 'ADIDAS-UB22-001',
                'short_description' => 'Performance running shoe',
                'description' => 'Adidas Ultraboost with responsive cushioning.',
                'price' => 179.99,
                'compare_at_price' => 199.99,
                'cost_price' => 100.00,
                'stock_quantity' => 100,
                'track_inventory' => true,
                'low_stock_threshold' => 15,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Adidas',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Adidas NMD R1',
                'sku' => 'ADIDAS-NMD-001',
                'short_description' => 'Lifestyle shoe with boost',
                'description' => 'Adidas NMD R1 with modern design.',
                'price' => 139.99,
                'compare_at_price' => 159.99,
                'cost_price' => 80.00,
                'stock_quantity' => 130,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Clothing',
                'brand_name' => 'Adidas',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Adidas Essentials T-Shirt',
                'sku' => 'ADIDAS-SHIRT-001',
                'short_description' => 'Classic cotton t-shirt',
                'description' => 'Adidas essentials cotton t-shirt.',
                'price' => 24.99,
                'compare_at_price' => 34.99,
                'cost_price' => 12.00,
                'stock_quantity' => 600,
                'track_inventory' => true,
                'low_stock_threshold' => 60,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Adidas',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Adidas Tiro Track Jacket',
                'sku' => 'ADIDAS-JACKET-001',
                'short_description' => 'Classic training jacket',
                'description' => 'Adidas Tiro track jacket.',
                'price' => 79.99,
                'compare_at_price' => 99.99,
                'cost_price' => 45.00,
                'stock_quantity' => 80,
                'track_inventory' => true,
                'low_stock_threshold' => 12,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Clothing',
                'brand_name' => 'Adidas',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],
            [
                'name' => 'Adidas Climalite Pants',
                'sku' => 'ADIDAS-PANTS-001',
                'short_description' => 'Moisture-wicking athletic pants',
                'description' => 'Adidas climalite training pants.',
                'price' => 69.99,
                'compare_at_price' => 89.99,
                'cost_price' => 38.00,
                'stock_quantity' => 120,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Clothing',
                'brand_name' => 'Adidas',
                'collection_name' => null,
                'gender_name' => 'Unisex',
                'scent_family_name' => null,
            ],

            // Category: Home & Garden - Brand: Dyson
            [
                'name' => 'Dyson V15 Detect',
                'sku' => 'DYSON-V15-001',
                'short_description' => 'Cordless vacuum cleaner',
                'description' => 'Dyson V15 with laser detection.',
                'price' => 749.00,
                'compare_at_price' => 799.00,
                'cost_price' => 450.00,
                'stock_quantity' => 25,
                'track_inventory' => true,
                'low_stock_threshold' => 5,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Home & Garden',
                'brand_name' => 'Dyson',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Dyson Humidifier',
                'sku' => 'DYSON-HUMID-001',
                'short_description' => 'Smart humidifier with oscillation',
                'description' => 'Dyson humidifier with UV-C light.',
                'price' => 399.00,
                'compare_at_price' => 449.00,
                'cost_price' => 240.00,
                'stock_quantity' => 40,
                'track_inventory' => true,
                'low_stock_threshold' => 8,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Home & Garden',
                'brand_name' => 'Dyson',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Dyson Air Purifier',
                'sku' => 'DYSON-AP-001',
                'short_description' => 'Smart air purifier with heater',
                'description' => 'Dyson Purifier Hot+Cool with HEPA filter.',
                'price' => 599.00,
                'compare_at_price' => 649.00,
                'cost_price' => 360.00,
                'stock_quantity' => 35,
                'track_inventory' => true,
                'low_stock_threshold' => 7,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Home & Garden',
                'brand_name' => 'Dyson',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Dyson Hair Dryer',
                'sku' => 'DYSON-DRYER-001',
                'short_description' => 'High-tech hair dryer',
                'description' => 'Dyson Supersonic hair dryer.',
                'price' => 429.00,
                'compare_at_price' => 479.00,
                'cost_price' => 260.00,
                'stock_quantity' => 60,
                'track_inventory' => true,
                'low_stock_threshold' => 12,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Home & Garden',
                'brand_name' => 'Dyson',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
            [
                'name' => 'Dyson Lighting',
                'sku' => 'DYSON-LIGHT-001',
                'short_description' => 'Intelligent LED task light',
                'description' => 'Dyson Lightcycle desk lamp.',
                'price' => 549.00,
                'compare_at_price' => 599.00,
                'cost_price' => 330.00,
                'stock_quantity' => 50,
                'track_inventory' => true,
                'low_stock_threshold' => 10,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_bestseller' => false,
                'category_name' => 'Home & Garden',
                'brand_name' => 'Dyson',
                'collection_name' => null,
                'gender_name' => null,
                'scent_family_name' => null,
            ],
        ];

        // Insert products
        foreach ($products as $productData) {
            $categoryName = $productData['category_name'];
            $brandName = $productData['brand_name'];
            $collectionName = $productData['collection_name'];
            $genderName = $productData['gender_name'];
            $scentFamilyName = $productData['scent_family_name'];

            $product = Product::create([
                'name' => $productData['name'],
                'sku' => $productData['sku'],
                'short_description' => $productData['short_description'],
                'description' => $productData['description'],
                'price' => $productData['price'],
                'compare_at_price' => $productData['compare_at_price'],
                'cost_price' => $productData['cost_price'],
                'stock_quantity' => $productData['stock_quantity'],
                'track_inventory' => $productData['track_inventory'],
                'low_stock_threshold' => $productData['low_stock_threshold'],
                'allow_backorder' => $productData['allow_backorder'],
                'is_active' => $productData['is_active'],
                'is_featured' => $productData['is_featured'],
                'is_new' => $productData['is_new'],
                'is_bestseller' => $productData['is_bestseller'],
                'category_id' => $categories->where('name', $categoryName)->first()?->id,
                'brand_id' => $brands->where('name', $brandName)->first()?->id,
                'collection_id' => $collectionName ? $collections->where('name', $collectionName)->first()?->id : null,
                'gender_id' => $genderName ? $genders->where('name', $genderName)->first()?->id : null,
                'scent_family_id' => $scentFamilyName ? $scentFamilies->where('name', $scentFamilyName)->first()?->id : null,
                'sort_order' => 0,
                'view_count' => rand(10, 500),
                'sold_count' => rand(0, 100),
                'rating' => rand(30, 50) / 10,
                'rating_count' => rand(0, 50),
            ]);
        }
    }
}
