<?php

namespace Database\Seeders;

use App\Models\Admin\Brand\Brand;
use App\Models\Admin\Category\Category;
use App\Models\Admin\Collection\Collection;
use App\Models\Admin\Gender\Gender;
use App\Models\Admin\Product\Product;
use App\Models\Admin\ScentFamily\ScentFamily;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        $brands = Brand::all();
        $collections = Collection::all();
        $genders = Gender::all();
        $scentFamilies = ScentFamily::all();

        // Perfume products with variations
        $products = [
            // Dior Perfumes
            [
                'name' => 'Sauvage Eau de Parfum',
                'sku' => 'DIOR-SAU-EDP-100',
                'short_description' => 'Radically fresh composition with Calabrian bergamot',
                'description' => 'Sauvage Eau de Parfum by Dior is a wildly fresh fragrance with Calabrian bergamot notes and Ambroxan. An iconic masculine scent that is both powerful and noble.',
                'price' => 135.00,
                'compare_at_price' => 150.00,
                'cost_price' => 80.00,
                'stock_quantity' => 150,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Dior',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Miss Dior Blooming Bouquet',
                'sku' => 'DIOR-MDB-EDT-100',
                'short_description' => 'Fresh and tender peony notes',
                'description' => 'Miss Dior Blooming Bouquet is a fresh and tender fragrance with notes of peony, rose, and white musk. A romantic and elegant scent for modern women.',
                'price' => 128.00,
                'compare_at_price' => 140.00,
                'cost_price' => 75.00,
                'stock_quantity' => 120,
                'track_inventory' => true,
                'low_stock_threshold' => 18,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Dior',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'J\'adore Eau de Parfum',
                'sku' => 'DIOR-JAD-EDP-100',
                'short_description' => 'Luminous floral bouquet',
                'description' => 'J\'adore by Dior is an extraordinary floral bouquet of the most beautiful flowers: Ylang-Ylang, Damask Rose, and Jasmine. A timeless and sensual fragrance.',
                'price' => 145.00,
                'compare_at_price' => 160.00,
                'cost_price' => 85.00,
                'stock_quantity' => 100,
                'track_inventory' => true,
                'low_stock_threshold' => 15,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Dior',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Homme Intense',
                'sku' => 'DIOR-HOM-EDP-100',
                'short_description' => 'Powerful woody fragrance',
                'description' => 'Dior Homme Intense is a sophisticated and sensual woody fragrance with iris and vetiver. Perfect for the modern gentleman.',
                'price' => 142.00,
                'compare_at_price' => 155.00,
                'cost_price' => 82.00,
                'stock_quantity' => 85,
                'track_inventory' => true,
                'low_stock_threshold' => 12,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Dior',
                'collection_name' => 'Luxury Collection',
                'gender_name' => 'Male',
                'scent_family_name' => 'Woody',
            ],

            // Chanel Perfumes
            [
                'name' => 'Chanel No. 5 Eau de Parfum',
                'sku' => 'CHANEL-NO5-EDP-100',
                'short_description' => 'The world\'s most iconic fragrance',
                'description' => 'Chanel No. 5 is the ultimate expression of femininity and elegance. A timeless floral aldehyde fragrance with notes of rose, jasmine, and vanilla.',
                'price' => 155.00,
                'compare_at_price' => 170.00,
                'cost_price' => 90.00,
                'stock_quantity' => 200,
                'track_inventory' => true,
                'low_stock_threshold' => 25,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Chanel',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Bleu de Chanel Eau de Parfum',
                'sku' => 'CHANEL-BLU-EDP-100',
                'short_description' => 'Woody aromatic fragrance for men',
                'description' => 'Bleu de Chanel EDP is an aromatic woody fragrance with notes of citrus, labdanum, and sandalwood. A refined and sophisticated scent.',
                'price' => 148.00,
                'compare_at_price' => 165.00,
                'cost_price' => 88.00,
                'stock_quantity' => 180,
                'track_inventory' => true,
                'low_stock_threshold' => 22,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Chanel',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Male',
                'scent_family_name' => 'Woody',
            ],
            [
                'name' => 'Coco Mademoiselle Eau de Parfum',
                'sku' => 'CHANEL-COCO-EDP-100',
                'short_description' => 'Fresh oriental fragrance',
                'description' => 'Coco Mademoiselle is a fresh and modern oriental fragrance with notes of orange, patchouli, and vanilla. Sensual yet refined.',
                'price' => 152.00,
                'compare_at_price' => 168.00,
                'cost_price' => 89.00,
                'stock_quantity' => 165,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Chanel',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Female',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Chance Eau Tendre',
                'sku' => 'CHANEL-CHA-EDT-100',
                'short_description' => 'Delicate fruity-floral fragrance',
                'description' => 'Chance Eau Tendre is a tender and delicate fragrance with notes of grapefruit, quince, and white musk. Fresh and romantic.',
                'price' => 138.00,
                'compare_at_price' => 150.00,
                'cost_price' => 78.00,
                'stock_quantity' => 140,
                'track_inventory' => true,
                'low_stock_threshold' => 18,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Chanel',
                'collection_name' => 'Summer Scents',
                'gender_name' => 'Female',
                'scent_family_name' => 'Fresh',
            ],

            // Tom Ford Perfumes
            [
                'name' => 'Black Orchid Eau de Parfum',
                'sku' => 'TF-BLK-EDP-100',
                'short_description' => 'Luxurious and sensual dark fragrance',
                'description' => 'Tom Ford Black Orchid is a luxurious and sensual fragrance with notes of black truffle, ylang-ylang, and dark chocolate. Bold and sophisticated.',
                'price' => 185.00,
                'compare_at_price' => 205.00,
                'cost_price' => 110.00,
                'stock_quantity' => 90,
                'track_inventory' => true,
                'low_stock_threshold' => 12,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Tom Ford',
                'collection_name' => 'Luxury Collection',
                'gender_name' => 'Unisex',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Oud Wood Eau de Parfum',
                'sku' => 'TF-OUD-EDP-100',
                'short_description' => 'Rare oud wood with exotic spices',
                'description' => 'Tom Ford Oud Wood features rare oud wood, rosewood, cardamom, and sandalwood. A rich and smooth woody composition.',
                'price' => 295.00,
                'compare_at_price' => 320.00,
                'cost_price' => 175.00,
                'stock_quantity' => 60,
                'track_inventory' => true,
                'low_stock_threshold' => 8,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Tom Ford',
                'collection_name' => 'Niche Perfumes',
                'gender_name' => 'Unisex',
                'scent_family_name' => 'Woody',
            ],
            [
                'name' => 'Lost Cherry Eau de Parfum',
                'sku' => 'TF-CHE-EDP-100',
                'short_description' => 'Gourmand cherry scent',
                'description' => 'Tom Ford Lost Cherry is a fruity gourmand fragrance with notes of black cherry, bitter almond, and tonka bean. Playful and seductive.',
                'price' => 325.00,
                'compare_at_price' => 350.00,
                'cost_price' => 195.00,
                'stock_quantity' => 45,
                'track_inventory' => true,
                'low_stock_threshold' => 6,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Tom Ford',
                'collection_name' => 'Limited Edition',
                'gender_name' => 'Unisex',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Tobacco Vanille Eau de Parfum',
                'sku' => 'TF-TOB-EDP-100',
                'short_description' => 'Opulent tobacco and vanilla blend',
                'description' => 'Tom Ford Tobacco Vanille is an opulent fragrance with notes of tobacco leaf, vanilla, cocoa, and tonka bean. Warm and enveloping.',
                'price' => 285.00,
                'compare_at_price' => 310.00,
                'cost_price' => 170.00,
                'stock_quantity' => 70,
                'track_inventory' => true,
                'low_stock_threshold' => 10,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Tom Ford',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Unisex',
                'scent_family_name' => 'Oriental',
            ],

            // Yves Saint Laurent Perfumes
            [
                'name' => 'Black Opium Eau de Parfum',
                'sku' => 'YSL-BOP-EDP-90',
                'short_description' => 'Addictive coffee and vanilla fragrance',
                'description' => 'YSL Black Opium is an addictive gourmand fragrance with notes of coffee, vanilla, and white flowers. Seductive and modern.',
                'price' => 125.00,
                'compare_at_price' => 140.00,
                'cost_price' => 72.00,
                'stock_quantity' => 200,
                'track_inventory' => true,
                'low_stock_threshold' => 25,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Yves Saint Laurent',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Female',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Y Eau de Parfum',
                'sku' => 'YSL-Y-EDP-100',
                'short_description' => 'Masculine aromatic fougère',
                'description' => 'YSL Y Eau de Parfum is a fresh and aromatic fougère fragrance with notes of bergamot, sage, and cedarwood. Confident and refined.',
                'price' => 115.00,
                'compare_at_price' => 128.00,
                'cost_price' => 68.00,
                'stock_quantity' => 175,
                'track_inventory' => true,
                'low_stock_threshold' => 22,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Yves Saint Laurent',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Libre Eau de Parfum',
                'sku' => 'YSL-LIB-EDP-90',
                'short_description' => 'Freedom in a bottle',
                'description' => 'YSL Libre is a bold floral fragrance with notes of lavender, orange blossom, and musk. A scent of freedom and independence.',
                'price' => 132.00,
                'compare_at_price' => 145.00,
                'cost_price' => 76.00,
                'stock_quantity' => 155,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Yves Saint Laurent',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Mon Paris Eau de Parfum',
                'sku' => 'YSL-MON-EDP-90',
                'short_description' => 'Passionate fruity floral fragrance',
                'description' => 'YSL Mon Paris is a passionate fruity floral with notes of strawberry, raspberry, pear, and patchouli. Romantic and feminine.',
                'price' => 128.00,
                'compare_at_price' => 142.00,
                'cost_price' => 74.00,
                'stock_quantity' => 130,
                'track_inventory' => true,
                'low_stock_threshold' => 18,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Yves Saint Laurent',
                'collection_name' => null,
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],

            // Creed Perfumes
            [
                'name' => 'Aventus Eau de Parfum',
                'sku' => 'CREED-AVE-EDP-100',
                'short_description' => 'Legendary fruity chypre fragrance',
                'description' => 'Creed Aventus is a legendary fragrance with notes of pineapple, birch, musk, and oakmoss. A scent of success and confidence.',
                'price' => 435.00,
                'compare_at_price' => 465.00,
                'cost_price' => 260.00,
                'stock_quantity' => 80,
                'track_inventory' => true,
                'low_stock_threshold' => 10,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Creed',
                'collection_name' => 'Niche Perfumes',
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Silver Mountain Water',
                'sku' => 'CREED-SMW-EDP-100',
                'short_description' => 'Fresh alpine fragrance',
                'description' => 'Creed Silver Mountain Water is a crisp and clean fragrance with notes of bergamot, green tea, and sandalwood. Refreshing and invigorating.',
                'price' => 395.00,
                'compare_at_price' => 420.00,
                'cost_price' => 235.00,
                'stock_quantity' => 65,
                'track_inventory' => true,
                'low_stock_threshold' => 8,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Creed',
                'collection_name' => 'Summer Scents',
                'gender_name' => 'Unisex',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Aventus for Her',
                'sku' => 'CREED-AVH-EDP-75',
                'short_description' => 'Feminine fruity floral',
                'description' => 'Creed Aventus for Her is a sophisticated fruity floral with notes of bergamot, rose, and musk. Elegant and powerful.',
                'price' => 415.00,
                'compare_at_price' => 445.00,
                'cost_price' => 248.00,
                'stock_quantity' => 55,
                'track_inventory' => true,
                'low_stock_threshold' => 7,
                'allow_backorder' => true,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Creed',
                'collection_name' => 'Niche Perfumes',
                'gender_name' => 'Female',
                'scent_family_name' => 'Fresh',
            ],

            // Giorgio Armani Perfumes
            [
                'name' => 'Acqua di Giò Profumo',
                'sku' => 'ARM-ADG-PRO-125',
                'short_description' => 'Marine aromatic fragrance',
                'description' => 'Armani Acqua di Giò Profumo is an intense marine aromatic with notes of bergamot, geranium, and patchouli. Fresh and masculine.',
                'price' => 118.00,
                'compare_at_price' => 132.00,
                'cost_price' => 70.00,
                'stock_quantity' => 190,
                'track_inventory' => true,
                'low_stock_threshold' => 24,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Giorgio Armani',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Sì Passione Eau de Parfum',
                'sku' => 'ARM-SI-PAS-100',
                'short_description' => 'Passionate floral fragrance',
                'description' => 'Armani Sì Passione is a vibrant floral fragrance with notes of pear, rose, and vanilla. Passionate and elegant.',
                'price' => 125.00,
                'compare_at_price' => 138.00,
                'cost_price' => 72.00,
                'stock_quantity' => 145,
                'track_inventory' => true,
                'low_stock_threshold' => 19,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Giorgio Armani',
                'collection_name' => null,
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Code Absolu',
                'sku' => 'ARM-CODE-ABS-110',
                'short_description' => 'Intense oriental woody',
                'description' => 'Armani Code Absolu is an intense oriental woody with notes of green mandarin, tonka bean, and vanilla. Sophisticated and seductive.',
                'price' => 135.00,
                'compare_at_price' => 148.00,
                'cost_price' => 78.00,
                'stock_quantity' => 110,
                'track_inventory' => true,
                'low_stock_threshold' => 15,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Giorgio Armani',
                'collection_name' => null,
                'gender_name' => 'Male',
                'scent_family_name' => 'Oriental',
            ],

            // Versace Perfumes
            [
                'name' => 'Eros Eau de Toilette',
                'sku' => 'VER-ERO-EDT-100',
                'short_description' => 'Passionate aromatic fougère',
                'description' => 'Versace Eros is a passionate aromatic fougère with notes of mint, green apple, and vanilla. Bold and seductive.',
                'price' => 95.00,
                'compare_at_price' => 108.00,
                'cost_price' => 55.00,
                'stock_quantity' => 220,
                'track_inventory' => true,
                'low_stock_threshold' => 28,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Versace',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'Bright Crystal Eau de Toilette',
                'sku' => 'VER-BRI-EDT-90',
                'short_description' => 'Luminous floral fragrance',
                'description' => 'Versace Bright Crystal is a luminous floral with notes of yuzu, peony, and musk. Fresh and feminine.',
                'price' => 88.00,
                'compare_at_price' => 98.00,
                'cost_price' => 50.00,
                'stock_quantity' => 195,
                'track_inventory' => true,
                'low_stock_threshold' => 24,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Versace',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Dylan Blue Pour Homme',
                'sku' => 'VER-DYL-EDT-100',
                'short_description' => 'Mediterranean woody fougère',
                'description' => 'Versace Dylan Blue is a Mediterranean woody fougère with notes of bergamot, grapefruit, and incense. Fresh and masculine.',
                'price' => 92.00,
                'compare_at_price' => 105.00,
                'cost_price' => 53.00,
                'stock_quantity' => 160,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Versace',
                'collection_name' => null,
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],

            // Gucci Perfumes
            [
                'name' => 'Guilty Eau de Parfum',
                'sku' => 'GUCCI-GUI-EDP-90',
                'short_description' => 'Floriental fragrance',
                'description' => 'Gucci Guilty is a warm floriental with notes of mandora, lilac, and patchouli. Bold and provocative.',
                'price' => 115.00,
                'compare_at_price' => 128.00,
                'cost_price' => 66.00,
                'stock_quantity' => 170,
                'track_inventory' => true,
                'low_stock_threshold' => 21,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Gucci',
                'collection_name' => null,
                'gender_name' => 'Female',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Bloom Eau de Parfum',
                'sku' => 'GUCCI-BLO-EDP-100',
                'short_description' => 'White floral fragrance',
                'description' => 'Gucci Bloom is a rich white floral with notes of jasmine, tuberose, and Rangoon creeper. Romantic and sensual.',
                'price' => 125.00,
                'compare_at_price' => 138.00,
                'cost_price' => 72.00,
                'stock_quantity' => 135,
                'track_inventory' => true,
                'low_stock_threshold' => 17,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Gucci',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],
            [
                'name' => 'Guilty Pour Homme',
                'sku' => 'GUCCI-GH-EDT-90',
                'short_description' => 'Aromatic fougère for men',
                'description' => 'Gucci Guilty Pour Homme is an aromatic fougère with notes of lavender, lemon, and patchouli. Modern and seductive.',
                'price' => 98.00,
                'compare_at_price' => 110.00,
                'cost_price' => 56.00,
                'stock_quantity' => 150,
                'track_inventory' => true,
                'low_stock_threshold' => 19,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Gucci',
                'collection_name' => null,
                'gender_name' => 'Male',
                'scent_family_name' => 'Fresh',
            ],

            // Hermès Perfumes
            [
                'name' => 'Terre d\'Hermès Eau de Toilette',
                'sku' => 'HER-TER-EDT-100',
                'short_description' => 'Woody spicy fragrance',
                'description' => 'Hermès Terre d\'Hermès is a woody spicy fragrance with notes of grapefruit, pepper, and vetiver. Earthy and refined.',
                'price' => 128.00,
                'compare_at_price' => 142.00,
                'cost_price' => 74.00,
                'stock_quantity' => 140,
                'track_inventory' => true,
                'low_stock_threshold' => 18,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Hermès',
                'collection_name' => 'Signature Collection',
                'gender_name' => 'Male',
                'scent_family_name' => 'Woody',
            ],
            [
                'name' => 'Twilly d\'Hermès Eau de Parfum',
                'sku' => 'HER-TWI-EDP-85',
                'short_description' => 'Spicy floral fragrance',
                'description' => 'Hermès Twilly is a spicy floral with notes of ginger, tuberose, and sandalwood. Youthful and vibrant.',
                'price' => 135.00,
                'compare_at_price' => 148.00,
                'cost_price' => 78.00,
                'stock_quantity' => 105,
                'track_inventory' => true,
                'low_stock_threshold' => 14,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => false,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Hermès',
                'collection_name' => null,
                'gender_name' => 'Female',
                'scent_family_name' => 'Floral',
            ],

            // Dolce & Gabbana Perfumes
            [
                'name' => 'The One Eau de Parfum',
                'sku' => 'DG-ONE-EDP-100',
                'short_description' => 'Oriental floral fragrance',
                'description' => 'Dolce & Gabbana The One is an oriental floral with notes of bergamot, lychee, and vanilla. Elegant and sophisticated.',
                'price' => 108.00,
                'compare_at_price' => 120.00,
                'cost_price' => 62.00,
                'stock_quantity' => 165,
                'track_inventory' => true,
                'low_stock_threshold' => 20,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Dolce & Gabbana',
                'collection_name' => 'Best Sellers',
                'gender_name' => 'Female',
                'scent_family_name' => 'Oriental',
            ],
            [
                'name' => 'Light Blue Eau de Toilette',
                'sku' => 'DG-LB-EDT-100',
                'short_description' => 'Fresh fruity floral',
                'description' => 'Dolce & Gabbana Light Blue is a fresh fruity floral with notes of apple, bluebell, and cedarwood. Perfect for summer.',
                'price' => 95.00,
                'compare_at_price' => 108.00,
                'cost_price' => 54.00,
                'stock_quantity' => 210,
                'track_inventory' => true,
                'low_stock_threshold' => 26,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Toilette',
                'brand_name' => 'Dolce & Gabbana',
                'collection_name' => 'Summer Scents',
                'gender_name' => 'Female',
                'scent_family_name' => 'Fresh',
            ],
            [
                'name' => 'The One For Men',
                'sku' => 'DG-ONM-EDP-100',
                'short_description' => 'Oriental spicy for men',
                'description' => 'Dolce & Gabbana The One For Men is an oriental spicy with notes of grapefruit, basil, and tobacco. Confident and charismatic.',
                'price' => 102.00,
                'compare_at_price' => 115.00,
                'cost_price' => 58.00,
                'stock_quantity' => 125,
                'track_inventory' => true,
                'low_stock_threshold' => 16,
                'allow_backorder' => false,
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_bestseller' => true,
                'category_name' => 'Eau de Parfum',
                'brand_name' => 'Dolce & Gabbana',
                'collection_name' => null,
                'gender_name' => 'Male',
                'scent_family_name' => 'Oriental',
            ],
        ];

        // Insert products
        foreach ($products as $productData) {
            $categoryName = $productData['category_name'];
            $brandName = $productData['brand_name'];
            $collectionName = $productData['collection_name'];
            $genderName = $productData['gender_name'];
            $scentFamilyName = $productData['scent_family_name'];

            $product = Product::create([
                'name' => $productData['name'],
                'sku' => $productData['sku'],
                'short_description' => $productData['short_description'],
                'description' => $productData['description'],
                'price' => $productData['price'],
                'compare_at_price' => $productData['compare_at_price'],
                'cost_price' => $productData['cost_price'],
                'stock_quantity' => $productData['stock_quantity'],
                'track_inventory' => $productData['track_inventory'],
                'low_stock_threshold' => $productData['low_stock_threshold'],
                'allow_backorder' => $productData['allow_backorder'],
                'is_active' => $productData['is_active'],
                'is_featured' => $productData['is_featured'],
                'is_new' => $productData['is_new'],
                'is_bestseller' => $productData['is_bestseller'],
                'category_id' => $categories->where('name', $categoryName)->first()?->id,
                'brand_id' => $brands->where('name', $brandName)->first()?->id,
                'collection_id' => $collectionName ? $collections->where('name', $collectionName)->first()?->id : null,
                'gender_id' => $genderName ? $genders->where('name', $genderName)->first()?->id : null,
                'scent_family_id' => $scentFamilyName ? $scentFamilies->where('name', $scentFamilyName)->first()?->id : null,
                'sort_order' => 0,
                'view_count' => rand(50, 1500),
                'sold_count' => rand(10, 500),
                'rating' => rand(38, 50) / 10,
                'rating_count' => rand(20, 250),
            ]);
        }
    }
}
